package interfaz;

import ParteDistribuida.InterfaceObtenerValores;
import java.rmi.Naming;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class InterfazParte2 extends javax.swing.JFrame {

     //Localiza el objeto distribuido
    private InterfaceObtenerValores obj;
    
    public void actualizar() throws RemoteException{
        while(true){
            
            numeroHormigasObrerasExterior.setText(String.valueOf(obj.getHormigasObrerasExterior()));
            numeroHormigasObrerasInterior.setText(String.valueOf(obj.getHormigasObrerasInterior()));
            numeroHormigasSoldadoInstruccion.setText(String.valueOf(obj.getHormigasSoldadoInstruccion()));
            numeroHormigasSoldadoInvasion.setText(String.valueOf(obj.getHormigasSoldadoInvasion()));
            numeroHormigasCriaZonaComer.setText(String.valueOf(obj.getHormigasCriaZonaParaComer()));
            numeroHormigasCriaRefugio.setText(String.valueOf(obj.getHormigasCriaRefugio()));
        }
    }
    
    /**
     * Creates new form InterfazParte2
     */
    public InterfazParte2() {
        initComponents();
        jLabelAmenaza.setText("No hay amenaza");
        
        try{
            obj = (InterfaceObtenerValores) Naming.lookup("//127.0.0.1/VistaNumeroHormigas");
           
            // creacion de hilos
            new Thread(new Runnable(){
                @Override
                public void run(){
                    try {
                        actualizar();
                    } catch (RemoteException ex) {
                        Logger.getLogger(InterfazParte2.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }).start();
            
            
            
        }
        catch (Exception e)
        {
            System.out.println("Excepción : " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numeroHormigasObrerasExterior = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numeroHormigasObrerasInterior = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numeroHormigasSoldadoInstruccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numeroHormigasSoldadoInvasion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numeroHormigasCriaZonaComer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        numeroHormigasCriaRefugio = new javax.swing.JTextField();
        botonAmenaza = new javax.swing.JButton();
        jLabelAmenaza = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Numero de hormigas obreras en el exterior:");

        numeroHormigasObrerasExterior.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numeroHormigasObrerasExterior.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Numero de hormigas obreras en el interior:");

        numeroHormigasObrerasInterior.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numeroHormigasObrerasInterior.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Numero de hormigas soldado haciendo instruccion:");

        numeroHormigasSoldadoInstruccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numeroHormigasSoldadoInstruccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Numero de hormigas soldado repeliendo una invasion:");

        numeroHormigasSoldadoInvasion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numeroHormigasSoldadoInvasion.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Numero de hormigas cria en la ZONA PARA COMER:");

        numeroHormigasCriaZonaComer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numeroHormigasCriaZonaComer.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Numero de hormigas cria en el REFUGIO:");

        numeroHormigasCriaRefugio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numeroHormigasCriaRefugio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botonAmenaza.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botonAmenaza.setText("Generar Amenaza Insecto Invasor");

        jLabelAmenaza.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelAmenaza.setText("Amenaza");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAmenaza)
                        .addGap(18, 18, 18)
                        .addComponent(botonAmenaza))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeroHormigasObrerasInterior, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(93, 93, 93)
                            .addComponent(numeroHormigasObrerasExterior, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeroHormigasSoldadoInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeroHormigasSoldadoInvasion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeroHormigasCriaZonaComer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeroHormigasCriaRefugio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(numeroHormigasObrerasExterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numeroHormigasObrerasInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numeroHormigasSoldadoInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numeroHormigasSoldadoInvasion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numeroHormigasCriaZonaComer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numeroHormigasCriaRefugio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAmenaza)
                    .addComponent(jLabelAmenaza))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazParte2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazParte2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazParte2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazParte2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazParte2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAmenaza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAmenaza;
    private javax.swing.JTextField numeroHormigasCriaRefugio;
    private javax.swing.JTextField numeroHormigasCriaZonaComer;
    private javax.swing.JTextField numeroHormigasObrerasExterior;
    private javax.swing.JTextField numeroHormigasObrerasInterior;
    private javax.swing.JTextField numeroHormigasSoldadoInstruccion;
    private javax.swing.JTextField numeroHormigasSoldadoInvasion;
    // End of variables declaration//GEN-END:variables
}
